### ISSUE TITLE
sylu.site

### ISSUE THREAD

**Issue by laenix** [fzf404/home#2]
友链地址: https://www.sylu.site/

如何称呼呢: laenix

头像的地址: https://www.sylu.site/upload/2021/10/d40ec9feeb5f98f99e3a99b5f35188f9-079847e060b744f0aed67dcf3812100d.jpeg

**Comment by fzf404** [comment]
好耶

**Comment by fzf404** [comment]
一个小时后cdn缓存自动清掉就加上啦

**Comment by fzf404** [comment]
一个小时后cdn缓存自动清掉就加上啦
