### ISSUE TITLE
mzmm403

### ISSUE THREAD

**Issue by mzmm403** [fzf404/home#3]
友链地址: https://www.mzmm403.top/test1/

如何称呼呢: mzmm403

头像的地址: https://github.com/mzmm403

**Comment by fzf404** [comment]
无法访问

**Comment by mzmm403** [comment]
> 无法访问

什么无法访问啊 是友链还是头像地址 那个头像地址我填的是github的主页 我不知道那个头像是什么意思

**Comment by fzf404** [comment]
![Uploading 2EE608B5-F7D3-4CF7-AFC8-6D9F79FCE6B7.png…]()
