### ISSUE TITLE
加个友链吧～

### ISSUE THREAD

**Issue by Skywt2003** [fzf404/home#5]
友链地址: https://skywt.cn/

如何称呼呢: SkyWT

头像的地址: https://blog.skywt.cn/usr/themes/Daydream/assets/img/avatar.png

偶然看到博主的网站，这个设计风格很有特色诶

（而且我可能和博主一样比较左，键政爱好者（不是））

来加个友链吧～

**Comment by fzf404** [comment]
好呀，明天会加上的，现在已经上床了（x

**Comment by Skywt2003** [comment]
这么早睡觉嘛（（

**Comment by fzf404** [comment]
2333最近比较忙啦，已经加上啦，等cdn刷新就有了～

**Comment by fzf404** [comment]
我的昵称少打了个f（x

**Comment by Skywt2003** [comment]
加上了😂
