### ISSUE TITLE
👀

### ISSUE THREAD

**Issue by iGxnon** [fzf404/home#8]
如何称呼: iGxnon

友链地址: https://blog.skygard.work/

头像地址: https://blog.skygard.work/images/logo.png

自我介绍: 相对失败的泡泡

**Comment by fzf404** [comment]
好哦，这几天有点忙，下个月忙完了就加上！

**Comment by iGxnon** [comment]
> 好哦，这几天有点忙，下个月忙完了就加上！

好，我给你的先加上吧

**Comment by fzf404** [comment]
修炼中的全栈开发者，社会主义接班人

**Comment by fzf404** [comment]
加上啦～
