### ISSUE TITLE
申请友链：from 爱飞的鸟

### ISSUE THREAD

**Issue by aFlyBird0** [fzf404/home#9]
如何称呼: 爱飞的鸟

友链地址: https://blog.aflybird.cn

头像地址: https://avatars.githubusercontent.com/u/36830265

自我介绍: 会写点文章，很想认真搞技术

**Comment by aFlyBird0** [comment]
可以来这里加友链 ！❤️ https://github.com/aFlyBird0/blog-friends/issues/new?assignees=aFlyBird0&labels=&template=apply-friend-link.yml&title=%E7%94%B3%E8%AF%B7%E5%8F%8B%E9%93%BE:+

**Comment by fzf404** [comment]
稍等哦，最近在重构我的网站，重构完成后就加上！

**Comment by fzf404** [comment]
抱歉拖了这么久，已经加上啦！
